# Imagem de Origem
FROM node:12.18.1
# Diretório de trabalho(é onde a aplicação ficará dentro do container).

# Adicionando `/app/node_modules/.bin` para o $PATH

# Instalando dependências da aplicação e armazenando em cache.

RUN npm install 
# Inicializa a aplicação
CMD ["npm", "start"]